CREATE TABLE USUARIO (
  ID_USUARIO NUMBER NOT NULL,
  PIX VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  SENHA VARCHAR2(50) NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  ENDERECO VARCHAR2(255) NOT NULL,
  CPF CHAR(11) NOT NULL,
  CIDADE VARCHAR2(255) NOT NULL,
  ESTADO VARCHAR2(50) NOT NULL,
  TELEFONE CHAR(11) NOT NULL,
  DELETADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_USUARIO),
  UNIQUE (PIX, EMAIL,CPF)
);

CREATE TABLE PRODUTO (
  ID_PRODUTO NUMBER NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  DESCRICAO VARCHAR2(255) NOT NULL,
  QUANTIDADE NUMBER NOT NULL,
  TIPO VARCHAR2(1),
  VALOR NUMBER(10,2),
  ID_USUARIO NUMBER NOT NULL,
  DELETADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_PRODUTO),
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CUPOM (
  ID_CUPOM NUMBER NOT NULL,
  DESCONTO NUMBER(10,2),
  DELETADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_CUPOM)
);

CREATE TABLE PEDIDO (
  ID_PEDIDO NUMBER NOT NULL,
  ID_CUPOM NUMBER,
  ID_USUARIO NUMBER NOT NULL,
  VALOR_FINAL NUMBER(10,2),
  DELETADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_PEDIDO),
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
  FOREIGN KEY (ID_CUPOM) REFERENCES CUPOM(ID_CUPOM)
);

CREATE TABLE PRODUTO_PEDIDO (
  ID_PRODUTO_PEDIDO NUMBER NOT NULL,
  ID_PRODUTO NUMBER NOT NULL,
  ID_PEDIDO NUMBER NOT NULL,
  QUANTIDADE NUMBER NOT NULL,
  VALOR NUMBER(10,2),
  DELETADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_PRODUTO_PEDIDO),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);